services:

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile
    ports:
      - "80:80"
    # MOUNT PUBLIC FILES AS READ-ONLY FOR NGINX
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./public:/var/www/html/public:ro
    depends_on:
      - php
    networks:
      - app

  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    volumes:
      - .:/var/www/html
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app

  postgres:
    image: postgres:18-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: yii3_rest_api_stub
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d yii3_rest_api_stub"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - app

networks:
  app:

# PERSIST POSTGRES DATA OUTSIDE THE CONTAINER LIFECYCLE
volumes:
  postgres_data:
